name: Backend deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./backend/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_BE_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}