name: Backend build + deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup ssh
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{secrets.SSH_HOST}}

      - uses: actions/checkout@v2

      - name: Enter Frontend dir
        run: cd ./backend
      
      - name: Add secrets
        run: ${{secrets.MAIL_SECRETS}} >> ./src/secrets.json

      - name: Deploy to Docker Host
        run: docker-compose -H ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:2375 up --build -d
